document.write('<center>')
document.write('<hr width=600 color=blue>')
document.write('<h1>Belajar Javascript</h1>')
document.write('<h2>PTIK UNS 2020</h2>')
document.write('<h4>NIM K3520057</h4>')
document.write('<hr width=800 color=brown>')
document.write('</center>')